%% PLOTS
% This function plots the joint positions, velocities, accelerations and
% torques over time. It is not a function but a main script so as to not
% count in the time measurement of the algorithms

%%% DO NOT INSERT ANY CLEAR! THE CODE USES DATA GENERATED BY COMPLETED %%%
%%%                          ALGORITHMS                                %%%                         

tindisp = t(1);
tfindisp = t(end);

figure
for i=1:num_of_joints
    subplot(4,2,i);
    plot(t,Q(i,:),'LineWidth',2);
    grid;
    textylabel = sprintf('q_%i [rad]',i);
    ylabel(textylabel);
    xlabel('time [s]');
    xlim([tindisp tfindisp]);
end


figure
for i=1:num_of_joints
    subplot(4,2,i);
    plot(t,dQ(i,:),'LineWidth',2);
    grid;
    textylabel = sprintf('dq_%i [rad/s]',i);
    ylabel(textylabel);
    xlabel('time [s]');
    xlim([tindisp tfindisp]);
end


figure
for i=1:num_of_joints
    subplot(4,2,i);
    plot(t,ddQ(i,:),'LineWidth',2);
    grid;
    textylabel = sprintf('ddq_%i [rad/s^2]',i);
    ylabel(textylabel);
    xlabel('time [s]');
    xlim([tindisp tfindisp]);
end

figure
for i=1:num_of_joints
    subplot(4,2,i);
    plot(t(1:6000),TAU_HAT(i,1:6000),'LineWidth',2);
    grid;
    textylabel = sprintf('_%i [Nm]',i);
    ylabel(['\tau' textylabel]);
    xlabel('time [s]');
    xlim([tindisp 60]);
end

